version: "3.2"

services:
  backend:
    image: 360composer-backend
    build:
      context: ./scene-editor/backend
      dockerfile: ops/Dockerfile
    pull_policy: never
    environment:
        DATABASE_URI: "postgresql://postgres:${DATABASE_PASSWORD}@postgres/postgres_pcitvr"
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    volumes:
      - type: bind
        source: ${PATH_ASSETS}
        target: /assets
    command: bash -c "/entrypoint.sh"
    depends_on: [postgres, redis]
    restart: unless-stopped

  redis:
    image: redis
    restart: unless-stopped

  postgres:
    image: postgres:15
    volumes:
      - type: bind
        source: ${PATH_DB}
        target: /var/lib/postgresql/data
    environment:
        - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        - POSTGRES_USER=postgres
        - POSTGRES_DB=postgres_pcitvr
    restart: unless-stopped

  frontend:
    image: 360composer-frontend
    build:
      context: ./scene-editor/frontend
      dockerfile: ops/Dockerfile
    pull_policy: never
    volumes:
      - type: bind
        source: ${NGINX_CONF:-./conf/nginx-prod.conf}
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - type: bind
        source: ${SSL_CERT:-/dev/null}
        target: /etc/ssl/certs/certificate.cer
        read_only: true
      - type: bind
        source: ${SSL_PRIVKEY:-/dev/null}
        target: /etc/ssl/private/certificate.key
        read_only: true
      - type: bind
        source: ${PATH_ASSETS}
        target: /assets
        read_only: false
    ports:
      - 8080:8080
    restart: unless-stopped

