version: '3'
services:
  backend:
    ports:
        - 5000:5000
    environment:
        DEBUG: 1

  postgres:
    ports:
      - 5433:5432

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    depends_on: 
      - postgres
    ports:
      - 8081:8080

  nginx:
    build:
      dockerfile: ./ops/Dockerfile.nginx
