"""Removed project id from assets

Revision ID: 2031b2240384
Revises: 7f8d960d8c44
Create Date: 2021-12-31 13:09:10.356757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2031b2240384'
down_revision = '7f8d960d8c44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('asset_project_id_fkey', 'asset', type_='foreignkey')
    op.drop_column('asset', 'project_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('project_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('asset_project_id_fkey', 'asset', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###
