"""add usertest table

Revision ID: 9bde56981cf8
Revises: 2031b2240384
Create Date: 2023-01-23 10:32:12.186250

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision = '9bde56981cf8'
down_revision = '2031b2240384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_test',
    sa.Column('id', UUID(), nullable=False),
    sa.Column('device', sa.String(128)),
    sa.Column('os', sa.String(128)),
    sa.Column('workedbaby', sa.Boolean),
    sa.Column('commentsbaby', sa.String(1024)),
    sa.Column('workedaframe', sa.Boolean),
    sa.Column('commentsaframe', sa.String(1024)),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    
    )
    # ### end Alembic commands ###


def downgrade():
    pass