FROM node:18 as build

ARG BASEPATH=/app
ENV BASEPATH=$BASEPATH

COPY /scene-editor/frontend/package.json /app/scene-editor-frontend/package.json
COPY /scene-editor/frontend/package-lock.json /app/scene-editor-frontend/package-lock.json
WORKDIR /app/scene-editor-frontend
RUN npm ci && npm cache clean --force

COPY /scene-editor/frontend/src /app/scene-editor-frontend/src
COPY /scene-editor/frontend/public /app/scene-editor-frontend/public
COPY /scene-editor/frontend/tsconfig.json /app/scene-editor-frontend/tsconfig.json

ENV HOST 0.0.0.0
ENV NODE_OPTIONS --openssl-legacy-provider

ENTRYPOINT ["npm", "start"]
